name: Release

env:
  APP_PROJECT_NAME: Trophy.App
  APP_NAME: as-trophy
  DOTNET_VERSION: '6.0'
  RELEASE_TAG_INPUT: ${{ github.event.release.tag_name }}
  BUILD_ID: ${{ github.run_number }}
  COMMIT_ID: ${{ github.sha }}

on:
  release:
    types: [published]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit testing
    steps:
      - uses: actions/checkout@v2.1.0
      - run: dotnet test
          
  build-app:
    runs-on: ubuntu-latest
    needs: unit-test
    name: Build app

    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v3

      - name: Set up .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build ${{env.APP_PROJECT_NAME}}
        run: dotnet build ${{env.APP_PROJECT_NAME}} -c Release

      - name: Publish ${{env.APP_PROJECT_NAME}}
        run: dotnet publish ${{env.APP_PROJECT_NAME}} -c Release -p:CommitId=$COMMIT_ID -p:BuildId=$BUILD_ID -p:BuildTag=$RELEASE_TAG_INPUT -o ${{env.DOTNET_ROOT}}/${{env.APP_PROJECT_NAME}}

      - name: Upload ${{env.APP_PROJECT_NAME}}
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_PROJECT_NAME}}
          path: ${{env.DOTNET_ROOT}}/${{env.APP_PROJECT_NAME}}

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-app
    name: Deploy app
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download ${{env.APP_PROJECT_NAME}}
        uses: actions/download-artifact@v3
        with:
          name: ${{env.APP_PROJECT_NAME}}

      - name: Deploy to Azure App service ${{ env.APP_NAME }}
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE }}
          package: .
